ci:add clean-up before docker build

diff --git a/.github/workflows/snyk-scan.yml b/.github/workflows/snyk-scan.yml
--- a/.github/workflows/snyk-scan.yml
+++ b/.github/workflows/snyk-scan.yml
@@ -11,64 +11,64 @@ on:
       - devops/snyk-integration
 
 jobs:
-  snyk_scan_test:
-    if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
+  # snyk_scan_test:
+  #   if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@master
 
-      - uses: snyk/actions/setup@master
+  #     - uses: snyk/actions/setup@master
 
-      - uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
+  #     - uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.10'
       
-      - name: Build the docker image
-        run: |
-          docker rmi $(docker images -a -q) 
-          docker build -t h2o-llm-studio .
+  #     - name: Build the docker image
+  #       run: |
+  #         docker rmi $(docker images -a -q) 
+  #         docker build -t h2o-llm-studio .
       
-      - name: Get storage usage (debugging)
-        run: |
-          docker images
-          df -H .
-          pwd
-          sudo du -h .
+  #     - name: Get storage usage (debugging)
+  #       run: |
+  #         docker images
+  #         df -H .
+  #         pwd
+  #         sudo du -h .
       
-      - name: Scan the docker image
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
-        id: docker
-        run: |
-          snyk container test \
-            h2o-llm-studio \
-            -d \
-            --file=Dockerfile
+  #     - name: Scan the docker image
+  #       continue-on-error: true
+  #       env:
+  #         SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
+  #       id: docker
+  #       run: |
+  #         snyk container test \
+  #           h2o-llm-studio \
+  #           -d \
+  #           --file=Dockerfile
         
-      - name: Scan python dependencies
-        id: python
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
-        run: |
-          make setup
-          snyk test \
-            -d \
-            --file=Pipfile \
-            --package-manager=pipenv \
-            --command=python3.10 \
-            --skip-unresolved 
+  #     - name: Scan python dependencies
+  #       id: python
+  #       continue-on-error: true
+  #       env:
+  #         SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
+  #       run: |
+  #         make setup
+  #         snyk test \
+  #           -d \
+  #           --file=Pipfile \
+  #           --package-manager=pipenv \
+  #           --command=python3.10 \
+  #           --skip-unresolved 
       
-      - name: Check Snyk scan results
-        if: steps.docker.outcome == 'failure' || steps.python.outcome == 'failure'
-        shell: bash
-        run: |
-          echo "[warning] Please solve the fixable security vulnerabilities found in failed steps!
-                Snyk scan for Docker image - ${{ steps.docker.outcome }}
-                Snyk scan for Python dependencies - ${{ steps.python.outcome }}
-                "
-          exit 1
+  #     - name: Check Snyk scan results
+  #       if: steps.docker.outcome == 'failure' || steps.python.outcome == 'failure'
+  #       shell: bash
+  #       run: |
+  #         echo "[warning] Please solve the fixable security vulnerabilities found in failed steps!
+  #               Snyk scan for Docker image - ${{ steps.docker.outcome }}
+  #               Snyk scan for Python dependencies - ${{ steps.python.outcome }}
+  #               "
+  #         exit 1
     
         
   snyk_scan_monitor:
@@ -83,42 +83,45 @@ jobs:
         with:
           python-version: '3.10'
       
-      - name: Build the docker image
-        run: |
-          docker rmi $(docker images -a -q) 
-          docker build -t h2o-llm-studio .
-      
       - name: Get storage usage (debugging)
         run: |
           docker images
           df -H .
-          pwd
+          cd ~ & pwd
           sudo du -h .
       
-      - name: Monitor the docker image
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
-        run: |
-          snyk container monitor \
-            h2o-llm-studio \
-            -d \
-            --file=Dockerfile \
-            --org=h2o-llm-studio \
-            --project=H2O-LLM-STUDIO/h2o-llm-studio/${{ github.ref_name }}/Dockerfile
+      - name: Cleanup
+        run:
+          docker rmi $(docker images -a -q) 
+      
+      # - name: Build the docker image
+      #   run: |
+      #     docker build -t h2o-llm-studio .
+  
+      # - name: Monitor the docker image
+      #   continue-on-error: true
+      #   env:
+      #     SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
+      #   run: |
+      #     snyk container monitor \
+      #       h2o-llm-studio \
+      #       -d \
+      #       --file=Dockerfile \
+      #       --org=h2o-llm-studio \
+      #       --project=H2O-LLM-STUDIO/h2o-llm-studio/${{ github.ref_name }}/Dockerfile
         
-      - name: Monitor python dependencies
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
-        run: |
-          make setup
-          snyk monitor \
-            -d \
-            --file=Pipfile \
-            --package-manager=pipenv \
-            --command=python3.10 \
-            --skip-unresolved
-            --remote-repo-url=h2o-llm-studio/${{ github.ref_name }} \
-            --org=h2o-llm-studio \
-            --project=H2O-LLM-STUDIO/h2o-llm-studio/${{ github.ref_name }}/requirements.txt
+      # - name: Monitor python dependencies
+      #   continue-on-error: true
+      #   env:
+      #     SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
+      #   run: |
+      #     make setup
+      #     snyk monitor \
+      #       -d \
+      #       --file=Pipfile \
+      #       --package-manager=pipenv \
+      #       --command=python3.10 \
+      #       --skip-unresolved
+      #       --remote-repo-url=h2o-llm-studio/${{ github.ref_name }} \
+      #       --org=h2o-llm-studio \
+      #       --project=H2O-LLM-STUDIO/h2o-llm-studio/${{ github.ref_name }}/requirements.txt
